#default values
ROTATE_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFUALT = 0
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False

#Convolutions basic
FOUR_WAY_EDGE_DEFAULT = False
BLUR_2_DEFAULT = False
SHARPEN_DEFAULT = False
POINT_EDGE_DEFAULT = False
SHADOW_FLOOR_DEFAULT = 0
HIGHLIGHT_CEILING_DEFAULT = 0

#Colors
BACKGROUND_COLOR = '#242424'
WHITE = '#FFF'
GREY = 'grey'
BLUE = '#1f6aa5'
DARK_GRAY = '#4a4a4a'
CLOSE_RED = '#8a0606'

SLIDER_BG = '#64686b'

DROPDOWN_MAIN_COLOR = '#444'
DROWPDOWN_HOVER_COLOR = '#333'
DROWPDOWN_MENU_COLOR = '#666'